services:
  quackosm:
    profiles: [tools]
    build:
      context: docker/quackosm
    volumes:
      - ../../data:/data

  api:
    extends:
      file: ../../docker-compose-base.yaml
      service: api
    environment:
      BACKEND: DuckdbQuackosm
      DB: /data/landes-latest_nofilter_noclip_compact.parquet
    volumes:
      - ../../data:/data
